### ISSUE TITLE
Formatting

### ISSUE THREAD

**Issue by JPhilpin** [cleverdevil/micromemories#2]
My page is working perfectly - but am grappling with the styling. I have extended css on my site and the formatting is picking up styling that I do recognize as what I use for the <pre> tag ... but the text is coming out smaller - but when i modify the 'pre' css - it doesn’t affect that page - is there another tag being used?

My On This Day Page : http://john.philpin.com/on-this-day/

**Comment by cleverdevil** [comment]
Sounds like a CSS problem! Not sure how much I can help on this front. You may just have to tinker around a bit. If you're having trouble with your CSS, maybe ask in the Micro.blog #design Slack channel.

**Comment by JPhilpin** [comment]
i am and will - was just trying to establish what - if any - css tags you are using when you deliver the content to a site.

**Comment by JPhilpin** [comment]
thankyou
