### ISSUE TITLE
Invalid Date shown for hyperlink title

### ISSUE THREAD

**Issue by benjaminsnorris** [cleverdevil/micromemories#3]
Thanks so much for making this! It seems to be working properly and pulling in the posts. The hyperlink even works properly, and goes to the actual post. But the text of the hyperlink is "Invalid Date" instead of the actual date of the post. You can see it here: http://bsn.design/on-this-day/. If you're able to take a look at why that would be happening, that would be awesome. Thanks!

**Comment by JPhilpin** [comment]
I wonder if there is something about the format of the date being delivered from the template on the site - I just checked mine - and can't replicate.

http://john.philpin.com/on-this-day/

**Comment by JPhilpin** [comment]
however i notice our URK formats on the date are different ...

i have : 
https://john.philpin.com/2018/08/02/the-bullshit-web.html

ben has : 
http://www.bsn.design/2015/08/02/starclimberby-kenneth-oppel.html

maybe the 'www' is causing the problem ?

**Comment by benjaminsnorris** [comment]
Interesting! When I looked at the script that is being run, it looks like it grabs the date from `"date_published": "2015-08-02T23:58:41-06:00",` which seems like it should work. `published.toDateString();` seems to be what would generate the text for the link, and that is failing somehow. I tried taking off the time zone parameter that I passed in to see if that was throwing it off, but got the same results. 🤷‍♂️

**Comment by cleverdevil** [comment]
@benjaminsnorris I'll take a look at this soon! Can you make sure to post something today, so that I'll have some content to test against?

**Comment by benjaminsnorris** [comment]
Awesome, thanks! I posted something, so I should at least have one in there for today.

**Comment by cleverdevil** [comment]
Fixed in https://github.com/cleverdevil/micromemories/commit/839cf62478b2aa367e7fc3bc750d7b9a9d5b3850
