### ISSUE TITLE
Not capturing current day's posts

### ISSUE THREAD

**Issue by fmcpherson** [cleverdevil/micromemories#4]
On my blog at https://frankmcpherson.blog the One This Day script is not displaying current day's posts. The following is the content of my page.

<div id="on-this-day">
  Loading...
</div>
<script src="https://micromemories.cleverdevil.io/js?tz=US/Eastern"></script>

**Comment by cleverdevil** [comment]
I mentioned this over on Micro.blog to @manton, but I believe that this is a bug in your Micro.blog theme, which doesn't appear to have proper microformats on post pages. Once resolved, things should start working for you!

**Comment by cleverdevil** [comment]
Fixed as of now!

https://micro.blog/manton/765579
