### ISSUE TITLE
Controlling Look Of On This Day - Specifically Placing Of Date

### ISSUE THREAD

**Issue by JPhilpin** [cleverdevil/micromemories#5]
Finally worked out that my css file contained a div.post control which is where the look of the posts that appear in 'On This Day' is managed - so my problem reported earlier has gone away ... logging here so others will know if they hit a similar problem.

I am now just about there - **EXCEPT** date

If a post has a heading ... the heading is listed first, then the date, then the rest of the post.
if there is no heading - it obviously is just missing ... so - see attached screen shot - it LOOKS like the styling is inconsistent ... if I use an <h1> in my post

is it possible to set the date always at the top - or bottom of a post?
Maybe even not at all - since all posts listed On This Day will by definition have the same date - specifically todays - and thus redundant.

[screen shot 2018-08-11 at 5 18 09 pm](https://user-images.githubusercontent.com/18621554/43997207-9091402c-9d8a-11e8-87e5-4608475b311a.png)

**Comment by cleverdevil** [comment]
So, I took a look, and I personally am happy with the markup that is being generated. If you want to hide the dates, you can do so with CSS:

```css
#on-this-day .post-date {
    display: none;
}
```

Moving the date around on the page is a bit more difficult to do with just CSS, but could be done with changes to my JavaScript, I just don't know if it makes any sense. Is just hiding the date with the above CSS good enough for your use case?

**Comment by JPhilpin** [comment]
Let me try it out .... and use the above ... but now I see a page with both 2018 and 2016 posts I see the value of a date per post .... ... see other comment under Chirag ... sent that before I saw this.

**Comment by cleverdevil** [comment]
Very old issue. Closing for now. Feel free to open a new ticket.
