### ISSUE TITLE
On This Day page doesn't display

### ISSUE THREAD

**Issue by kimberlyhirsh** [cleverdevil/micromemories#8]
Instead of getting my On This Day page, I seem to get something from @odd's Micro.blog account.
![Screenshot 2021-07-19 154357](https://user-images.githubusercontent.com/5825002/126217886-e13d8be5-3da4-4200-94cb-bfa67ca611eb.jpg)

**Comment by cleverdevil** [comment]
Strange! Can you show me the source for your On This Day page?

**Comment by kimberlyhirsh** [comment]
Here's the code I have in the page:
```
<div id="on-this-day">
  Loading...
</div>

<script src="https://micromemories.cleverdevil.io/js?tz=US/Eastern"></script>
```

I'm seeing issues elsewhere on my site so this may be a m.b thing and not an on-this-day thing.

Yep, seems like this is actually an issue related to my domain name and m.b or something. Closing the issue!
